services:
  frontend-container:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
  backend-container:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      RAILS_ENV: development
      DB_HOST: mysql
      DB_NAME: ${USERNAME}
      DB_ROOT_PASS: ${ROOTPASS}
    depends_on:
      - db
    volumes:
      - ./backend:/ruby/
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    ports:
      - 4000:4000
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password