/* tslint:disable */
/* eslint-disable */
/**
 * API V1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TodosGet200ResponseItemsInner
 */
export interface TodosGet200ResponseItemsInner {
    /**
     * 
     * @type {number}
     * @memberof TodosGet200ResponseItemsInner
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof TodosGet200ResponseItemsInner
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof TodosGet200ResponseItemsInner
     */
    detail?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TodosGet200ResponseItemsInner
     */
    isDone?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TodosGet200ResponseItemsInner
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof TodosGet200ResponseItemsInner
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the TodosGet200ResponseItemsInner interface.
 */
export function instanceOfTodosGet200ResponseItemsInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function TodosGet200ResponseItemsInnerFromJSON(json: any): TodosGet200ResponseItemsInner {
    return TodosGet200ResponseItemsInnerFromJSONTyped(json, false);
}

export function TodosGet200ResponseItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodosGet200ResponseItemsInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'title': !exists(json, 'title') ? undefined : json['title'],
        'detail': !exists(json, 'detail') ? undefined : json['detail'],
        'isDone': !exists(json, 'isDone') ? undefined : json['isDone'],
        'createdAt': !exists(json, 'created_at') ? undefined : json['created_at'],
        'updatedAt': !exists(json, 'updated_at') ? undefined : json['updated_at'],
    };
}

export function TodosGet200ResponseItemsInnerToJSON(value?: TodosGet200ResponseItemsInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'title': value.title,
        'detail': value.detail,
        'isDone': value.isDone,
        'created_at': value.createdAt,
        'updated_at': value.updatedAt,
    };
}

