---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/todos":
    get:
      summary: Retrieves all todos
      responses:
        '200':
          description: Fetch All Todo
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        title:
                          type: string
                        detail:
                          type: string
                          nullable: true
                        isDone:
                          type: boolean
                        created_at:
                          type: string
                          format: datetime
                        updated_at:
                          type: string
                          format: datetime
  "/todos/{id}":
    get:
      summary: Retrieves todo
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Fetch Todo
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  detail:
                    type: string
                    nullable: true
                  isDone:
                    type: boolean
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
        '404':
          description: Not found
    patch:
      summary: Update todo
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Update Todo
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  detail:
                    type: string
                    nullable: true
                  isDone:
                    type: boolean
                  created_at:
                    type: string
                    format: datetime
                  updated_at:
                    type: string
                    format: datetime
        '404':
          description: Not found
    delete:
      summary: Remove todo
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
      responses:
        '200':
          description: Remove Todo
        '404':
          description: Not found
servers:
- url: http://localhost:4000
